### PR TITLE
Use http status code for not found detection

### LINKED ISSUE #9: Provider does not re-create deleted resources
### Steps to reproduce:

- Create a new server with terraform
- Delete the server through the cloudscale.ch web UI
- Run `terraform plan`

### Expected results: 

Terraform detects that the resource no longer exists and the plan would recreate the server

### Actual results:

`terraform plan` returns with exit code `1` and the following error message:

```
cloudscale_server.web-worker01: Refreshing state... (ID: 8befb05e-025c-431d-bcbb-abd8f4fb2593)

Error: Error refreshing state: 1 error(s) occurred:

* cloudscale_server.web-worker01: 1 error(s) occurred:

* cloudscale_server.web-worker01: cloudscale_server.web-worker01: Error retrieving server: detail: Not found
```
### Cause:

Not found detection in `resource_cloudscale_server.go` checks for the string `detail: Not Found.` but the API seems to return `detail: Not found`:

https://github.com/terraform-providers/terraform-provider-cloudscale/blob/33b91a5dcd600d0299c7a7c0ab7c684fa69e8e0d/cloudscale/resource_cloudscale_server.go#L271 

Newer versions of the cloudscale-go-sdk expose the HTTP status code. This could be used as an alternative to string matching.

### PR DESCRIPTION
**Pull request by ferdinandhuebner**
This fixes #9. 

I cherry-picked @davidhalter's updates to the cloudscale-go-sdk from PR #5, because this PR needs the updated sdk to access the HTTP status code returned by the API.

I am reusing the pattern that the OpenStack terraform provider uses for checking if a resource is deleted, see [terraform-provider-openstack/openstack/util.go](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/util.go) and [terraform-provider-openstack/openstack/resource_openstack_compute_instance_v2.go#L549](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_instance_v2.go#L549)

If I delete a server from the cloudscale.ch account and run `terraform plan`, terraform no longer returns an error but indicates that the resource needs to be created (not recreated).

I was unable to write an acceptance test for this, because it is unclear to me how I could call the cloudscale.ch API in a `TestStep`.

### CODE REVIEW

File: cloudscale/resource_cloudscale_server.go [hunk 1]
```diff
@@ -406,18 +400,10 @@ func resourceServerDelete(d *schema.ResourceData, meta interface{}) error {
...
-		d.SetId("")
-		return nil
-	}
-
 	if err != nil {
-		return fmt.Errorf("Error deleting Server: %s", err)
+		return CheckDeleted(d, err, "Error deleting Server")
 	}
 
-	d.SetId("")
```
Comment (davidhalter) [inline cloudscale/resource_cloudscale_server.go:419]: I'm not much of a terraform expert, but isn't this supposed to be here?

Comment (ferdinandhuebner) [reply cloudscale/resource_cloudscale_server.go:419]: I've been looking through a bunch of other providers (OpenStack, DigitalOcean and AWS) an none set the resource ID to the empty string during delete. 

[Official terraform docs for implementing destroy](https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-destroy) state:

> d.SetId("") is automatically called assuming delete returns no errors, but
> it is added here for explicitness.

I think we don't have to set it if there is no error.

Comment (davidhalter) [reply cloudscale/resource_cloudscale_server.go:419]: Awesome, thanks for looking it up!

**Review by davidhalter — APPROVED** [review]

**Comment by davidhalter** [comment]
Thanks a lot ferdinand!
